---
  version: '3'

  services:
    web:
      build: ./repo/lgtm-in-clone-backend
      ports:
        - 8000:8000
      volumes:
        - ./repo/lgtm-in-clone-backend:/app:delegated
        - express_node_modules:/app/node_modules

    mongodb:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ./repo/lgtm-in-clone-backend/data/db:/data/db

  volumes:
    express_node_modules: {}