---
  version: '3'

  services:
    frontend:
      build: ./repo/lgtm-in-clone-frontend
      ports:
        - 3000:3000
      command: sh -c "yarn start"
      volumes:
        - ./repo/lgtm-in-clone-frontend:/app:delegated
        - frontend_node_modules:/app/node_modules
      stdin_open: true
      tty: true

    backend:
      build: ./repo/lgtm-in-clone-backend
      ports:
        - 8000:8000
      volumes:
        - ./repo/lgtm-in-clone-backend:/app:delegated
        - backend_node_modules:/app/node_modules

    mongodb:
      image: mongo
      restart: always
      ports:
        - 27017:27017
      volumes:
        - ./repo/lgtm-in-clone-backend/data/db:/data/db

  volumes:
    backend_node_modules: {}
    frontend_node_modules: {}
